### ISSUE TITLE
keystone.py instructions are flipped

### ISSUE THREAD

**Issue by cpgmedialab** [RELNO/CityScope_Scanner_Python#6]
# current
keystone.py says "top left top right bottom left bottom right"

# should
"top right top left bottom right bottom left"

I thought we fixed it but current master wasn't synced??

**Comment by RELNO** [comment]
It is since https://github.com/RELNO/CityScope_Scanner_Python/commit/aa14973e8b94d0f4bf19ecc10313f7da823db42f. I've no control of which version was pulled on mac pro machine though.
